In [3]:
import numpy as np

# Criando um array da numpy

array = np.array([ 1, 2, 3, 4, 5 ])

mdim_array = np.array([ [ 1, 2, 3, 4, 5 ], [1, 2, 3, 4, 5] ])

# print(array)
# print(mdim_array)
# print(mdim_array[0])

[1 2 3 4 5]
[[1 2 3 4 5]
 [1 2 3 4 5]]


In [6]:
array = np.zeros(5)

print(array)

array = np.ones(5)

print(array)

array = np.empty(5)

print(array)

array = np.linspace(0, 10, num = 5)

print(array)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[ 0.   2.5  5.   7.5 10. ]


In [10]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

c = np.concatenate([a, b])

print(c)

a = np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]])
b = np.array([[6, 7, 8, 9, 10], [10, 9, 8, 7, 6]])

c = np.concatenate([a, b])

print(c)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 5  4  3  2  1]
 [ 6  7  8  9 10]
 [10  9  8  7  6]]
